user:
    accesskeyid: 98df355eb3314ca5a297dc863c9325fb
    secretaccesskey: 944cbc7628cc48fc9fb93540c5f10d2f
storage:
    redis:
        host: 127.0.0.1:6379
        password: ''
        defaultExpiration: 6000
log:
    file: 'idati.log'

live:
    playurl: rtmp://zhengfengplay1.baidudomainbcd.com/live/stream

